name: Run Postman Collection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-postman-collection:
    runs-on: windows-latest

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Node.js (required for Newman)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Run Postman Collection with environment file and generate HTML report
      - name: Run Postman Collection
        run: |
          newman run C:\Users\lenovo\AppData\Roaming\npm\Collection.json \
            --environment C:\Users\lenovo\AppData\Roaming\npm\Environment.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      # Upload HTML report as an artifact
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-html-report
          path: newman-report.html
